version: 2

sources:
  - name: snowflake_sample_data
    description: ' A sample database provided by Snowflake'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'Details about the sales in the store.'
  - name: jaffle_shop
    description: ' Source data of our jaffle shop'
    database: raw
    schema: JAFFLE_SHOP
    tables:
      - name: orders
        description: 'Details about the sales orders in the jaffle store.'
        